### ISSUE TITLE
babel error Transformation error (Missing initializer in const declaration)

### ISSUE THREAD

**Issue by esakal** [ElonVolo/evcodeshift#11]
Hello,
I'm getting an error when running evcodeshift.

```bash
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
 ERR /Users/e/test1-provider.tsx Transformation error (Missing initializer in const declaration. (16:26))
SyntaxError: Missing initializer in const declaration. (16:26)
    at instantiate (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parse-error/credentials.ts:62:21)
    at toParseError (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parse-error.ts:60:12)
    at JSXParserMixin.raise (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/tokenizer/index.ts:1490:19)
    at JSXParserMixin.parseVar (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:1522:16)
    at JSXParserMixin.parseVarStatement (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:1166:10)
    at JSXParserMixin.parseStatementContent (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:537:21)
    at JSXParserMixin.parseStatementLike (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:417:17)
    at JSXParserMixin.parseStatementListItem (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:366:17)
    at JSXParserMixin.parseExportDeclaration (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:2534:17)
    at JSXParserMixin.maybeParseExportDeclaration (/Users/eransakal/dev/github-public/xstate-hive/node_modules/@babel/parser/src/parser/statement.ts:2453:31)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
```

The file content is
```ts
import React, { useState, useMemo, PropsWithChildren } from 'react';
import {
  Test1Machine
} from './types';
import { createTest1Machine } from './utils/create-test1-machine';
import { useMachine } from '@xstate/react';
import { createTest1MachineLogger } from './utils/logger';
import { Test1Context } from './utils/test1-context';
import { updateExternalInfo } from './machine-actions/context/update-external-info';
import { onExternalInfoChanged } from './machine-services/on-external-info-changed';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const logger =  createTest1MachineLogger(
    'Test1Provider'
  );

export const Test1Provider: React.FC<PropsWithChildren> = ({ children }) => {
 
 const [machine] = useState(() => createTest1Machine());

  const [, , test1MachineService] = useMachine<Test1Machine>(machine, {
    actions: {
      updateExternalInfo 
    },
    services: {
      onExternalInfoChanged
     },
    guards: { },
  });


  const providerValue = useMemo(() => {
    return { test1MachineService };
  }, [test1MachineService]);

  return (
    <Test1Context.Provider value={providerValue}>
      {children}
    </Test1Context.Provider>
  );
};
```

Manually removing `: React.FC<PropsWithChildren>` will fix the babel error but it will not function correctly. For example running the method `findUseMachineAssignment` will not find the `useMachine` node unless I manually remove the generic type `<Text1Machine>`.

```ts
import {JSCodeshift, Transform} from 'jscodeshift'

function findUseMachineAssignment(j: JSCodeshift, ast: Collection<any>): j.VariableDeclarator | null {
  const assignment = ast.find(j.VariableDeclarator, {
    init: {
      callee: {name: 'useMachine'},
    },
  })

  if (assignment.length === 0) {
    // If assignment is not found, return null or handle the case accordingly
    return null
  }

  return assignment.at(0).get()
}

export const transform: Transform = (fileInfo, api, options) => {
  const j = api.jscodeshift
  const ast = j(fileInfo.source)

  const useMachineNode = findUseMachineAssignment(j, ast)

  console.dir(useMachineNode)
  return ast.toSource()
}

export default transform

```

Please advice
Thanks!
Eran

**Comment by eransakal** [comment]
I just realized that I need to pass `parser = tsx` Thanks

**Comment by esakal** [comment]
I just realized that I need to pass parser = tsx Thanks
